% Logistic regression
[X,y,X2,y1,y2,model] = run(struct( ...
'algorithm', 0, ...
'preprocessing_method', 'Z', ...
'postprocessing_critical', 0, ...
'feature_list', [101:117 200:217], ...
'be', 0 ... % basis expansion
));

% Linear SVM
fprintf('\n=============================\n');
[X,y,X2,y1,y2,model] = run(struct( ...
'algorithm', 4, ...
'preprocessing_method', 'Z', ...
'postprocessing_critical', 0, ...
'feature_list', [101:117 200:217], ...
'be', 0 ... % basis expansion
));

% Logistic regression with basis expansion
fprintf('\n=============================\n');
[X,y,X2,y1,y2,model] = run(struct( ...
'algorithm', 0, ...
'preprocessing_method', 'Z', ...
'postprocessing_critical', 0, ...
'feature_list', [101:117 200:217], ...
'be', 1 ... % basis expansion
));

% kernel SVM
fprintf('\n=============================\n');
[X,y,X2,y1,y2,model] = run(struct( ...
'algorithm', 2, ...
'preprocessing_method', 'Z', ...
'postprocessing_critical', 0, ...
'feature_list', [101:117 200:217], ...
'be', 0 ... % basis expansion
));

